version: "3.4"

services:
  afterimage.server:
    image: ${DOCKER_REGISTRY-}afterimageserver
    build:
      context: .
      dockerfile: Server/Dockerfile
    depends_on:
      - db
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
